spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ${JWT_SECRET:your-secret-key}
  expiration: 3600000 

app:
  frontend-url: ${FRONTEND_URL:http://localhost:4200}
