spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: cine
    password: cine123
    driver-class-name: org.postgresql.Driver

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET:your-secret-key}
  expiration: 3600000 
  
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:your-cloud-name}
  api-key: ${CLOUDINARY_API_KEY:your-api-key}
  api-secret: ${CLOUDINARY_API_SECRET:your-api-secret}
