spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=sales_db;encrypt=true;trustServerCertificate=true
    username: sa
    password: Cine123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8085

jwt:
  secret: ${JWT_SECRET:your-secret-key}