apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: pgdata-facturacion
  name: pgdata-facturacion
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
