spring.application.name=cinemax-backend

# Base de datos SQL Server Azure
spring.datasource.url=jdbc:sqlserver://cinemax-unmsm.database.windows.net:1433;database=cinemax_db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=admincinemax
spring.datasource.password=cinemaxabc123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# JWT
jwt.secret=M2U0ZTM0YjItMmYzZC00MWVkLWI4MzYtODhlYTQkOWY4Njg2Cg==

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# Puerto
server.port=8080