spring.application.name=cinemax-backend
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
springdoc.swagger-ui.path=/swagger-ui.html

# Importar del .env (Buscamos en la raíz y en la carpeta backend por si acaso)
spring.config.import=optional:file:.env[.properties],optional:file:backend/.env[.properties]

# Configuracion de la DB (SQL Server)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Configuracion de Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Seguridad
jwt.secret=${TOKEN_JWT_SECRET}
server.port=8080