spring.application.name=backend

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CineMax;encrypt=true;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.datasource.username=sa
spring.datasource.password=sa123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true