server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://postgres-facturacion:5432/sales_db
    username: ${DB_USER:cine}
    password: ${DB_PASSWORD:cine123}
    driver-class-name: org.postgresql.Driver

jwt:
  secret: ${JWT_SECRET:your-secret-key}

app:
  frontend-url: http://localhost:4200
