server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://postgres-usuarios:5432/usuarios_db
    username: ${DB_USER:cine}
    password: ${DB_PASSWORD:cine123}
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:tu-correo@gmail.com}
    password: ${MAIL_PASSWORD:tu-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:tu-cloud}
  api-key: ${CLOUDINARY_API_KEY:tu-key}
  api-secret: ${CLOUDINARY_API_SECRET:tu-secret}

app:
  frontend-url: ${FRONTEND_URL:http://localhost:4200}
