apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  DB_USER: cine
  DB_PASSWORD: cine123
  JWT_SECRET: tu-jwt-secreto
  MAIL_USERNAME: tu-correo@gmail.com
  MAIL_PASSWORD: tu-contrasena-correo
