apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  DB_USER: tu-usuario-db
  DB_PASSWORD: tu-password-db
  JWT_SECRET: tu-jwt-secreto
  MAIL_USERNAME: tu-correo@gmail.com
  MAIL_PASSWORD: tu-contrasena-correo
